contact_links:
  - about: Only a fool would request support
    name: By clicking this link I admit my inferiority
    url: >-
      https://github.com/comic3000/ForkedUp-blockchain/discussions/new?category=support
